name: CI SNAPSHOT

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  build_snapshot:
    runs-on: ubuntu-latest
    name: CI Build SNAPSHOT for ${{ github.ref_name }}
    steps:

      - uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Set up Gradle
        uses: spring-io/spring-gradle-build-action@v2
        with:
          java-version: 24

      - name: Build
        run: ./gradlew check

